python zip_dir_of_shps.py -i "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5/10m_cultural" -o "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5_zips"

python zip_dir_of_shps.py -i "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5/10m_physical" -o "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5_zips"

python zip_dir_of_shps.py -i "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5/50m_cultural" -o "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5_zips"

python zip_dir_of_shps.py -i "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5/50m_physical" -o "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5_zips"

python zip_dir_of_shps.py -i "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5/110m_cultural" -o "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5_zips"

python zip_dir_of_shps.py -i "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5/110m_physical" -o "/Volumes/Data/NaturalEarth/updates/natural_earth_update_1d5_zips"