# ---------------------------------------------------------------------------
# build_a7_ne_10m_admin_1_all.py
# Created on: Sun Nov 04 2012 03:08:00 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Conversion Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
ne_10m_admin_0_boundary_line_land_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_cultural\\ne_10m_admin_0_boundary_line_land.shp"
ne_10m_minor_islands_coastline_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_physical\\ne_10m_minor_islands_coastline.shp"
ne_10m_coastline_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_physical\\ne_10m_coastline.shp"
ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb_tmp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_scale_rank_geodb.gdb\\ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb_tmp"
ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_scale_rank_geodb.gdb\\ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb"
ne_10m_admin_1_label_points = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_label_points.gdb\\ne_10m_admin_1_label_points"
ne_10m_admin_1_states_provinces_lines_geodb = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_lines_geodb.gdb\\ne_10m_admin_1_states_provinces_lines_geodb"
ne_10m_admin_0_boundary_lines_map_units_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_cultural\\ne_10m_admin_0_boundary_lines_map_units.shp"
ne_10m_admin_1_states_provinces_scale_rank_geodb__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_scale_rank_geodb.gdb\\ne_10m_admin_1_states_provinces_scale_rank_geodb"
ne_10m_admin_1_seams_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_seams.shp"
ne_10m_admin_1_states_provinces_geodb = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_geodb.gdb\\ne_10m_admin_1_states_provinces_geodb"
ne_10m_admin_1_label_points_details = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_label_points.gdb\\ne_10m_admin_1_label_points_details"
ne_10m_admin_1_states_provinces_geodb_tmp__2_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_geodb.gdb\\ne_10m_admin_1_states_provinces_geodb"
ne_10m_admin_1_states_provinces_lakes_geodb = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_lakes_geodb.gdb\\ne_10m_admin_1_states_provinces_lakes_geodb"
ne_10m_lakes_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_physical\\ne_10m_lakes.shp"
ne_10m_lakes_tmp_admin_1_erase_shp = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_physical\\ne_10m_lakes_tmp_admin_1_erase.shp"
ne_10m_admin_1_states_provinces_geodb_tmp__4_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_geodb.gdb\\ne_10m_admin_1_states_provinces_geodb"
v10m_cultural__4_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural"
v10m_cultural__3_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural"
ne_10m_admin_1_states_provinces_lakes_shp__2_ = "ne_10m_admin_1_states_provinces_lakes_shp"
v10m_cultural__5_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural"
v10m_cultural__6_ = "C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural"
ne_10m_admin_1_states_provinces_shp = "ne_10m_admin_1_states_provinces_shp"

# Process: Feature To Polygon...
gp.FeatureToPolygon_management("C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_physical\\ne_10m_coastline.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_physical\\ne_10m_minor_islands_coastline.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_cultural\\ne_10m_admin_0_boundary_line_land.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_states_provinces_lines_geodb.gdb\\ne_10m_admin_1_states_provinces_lines_geodb;C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc3\\10m_cultural\\ne_10m_admin_0_boundary_lines_map_units.shp;C:\\ProjectFiles\\NaturalEarth\\nev_version_2d0d0_rc4\\10m_cultural\\ne_10m_admin_1_seams.shp", ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb_tmp, "", "ATTRIBUTES", ne_10m_admin_1_label_points)

# Process: Select...
gp.Select_analysis(ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb_tmp, ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb, "\"sr_adm0_a3\" <> ' '")

# Process: Select (2)...
gp.Select_analysis(ne_10m_admin_1_states_provinces_scale_rank_minor_islands_geodb, ne_10m_admin_1_states_provinces_scale_rank_geodb__2_, "\"adm0_sr\" <= 6")

# Process: Dissolve...
gp.Dissolve_management(ne_10m_admin_1_states_provinces_scale_rank_geodb__2_, ne_10m_admin_1_states_provinces_geodb, "adm1_code", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Join Field...
gp.JoinField_management(ne_10m_admin_1_states_provinces_geodb, "adm1_code", ne_10m_admin_1_label_points_details, "adm1_code", "")

# Process: Delete Field...
gp.DeleteField_management(ne_10m_admin_1_states_provinces_geodb_tmp__2_, "MIN_scaler")

# Process: Select (3)...
gp.Select_analysis(ne_10m_lakes_shp, ne_10m_lakes_tmp_admin_1_erase_shp, "\"admin\" = 'admin-0' Or \"admin\" = 'admin-0 more'")

# Process: Erase...
gp.Erase_analysis(ne_10m_admin_1_states_provinces_geodb_tmp__4_, ne_10m_lakes_tmp_admin_1_erase_shp, ne_10m_admin_1_states_provinces_lakes_geodb, "")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(ne_10m_admin_1_states_provinces_lakes_geodb, ne_10m_admin_1_states_provinces_lakes_shp__2_, "", "", "adm1_code adm1_code VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE;diss_me diss_me VISIBLE NONE;adm1_code_1 adm1_code_1 VISIBLE NONE;iso_3166_2 iso_3166_2 VISIBLE NONE;wikipedia wikipedia VISIBLE NONE;sr_sov_a3 sr_sov_a3 VISIBLE NONE;sr_adm0_a3 sr_adm0_a3 VISIBLE NONE;iso_a2 iso_a2 VISIBLE NONE;adm0_sr adm0_sr VISIBLE NONE;admin0_labelr admin0_labelr VISIBLE NONE;name name VISIBLE NONE;name_alt name_alt VISIBLE NONE;name_local name_local VISIBLE NONE;type type VISIBLE NONE;type_en type_en VISIBLE NONE;code_local code_local VISIBLE NONE;code_hasc code_hasc VISIBLE NONE;note note VISIBLE NONE;hasc_maybe hasc_maybe VISIBLE NONE;region region VISIBLE NONE;region_code region_code VISIBLE NONE;region_big region_big VISIBLE NONE;big_code big_code VISIBLE NONE;provnum_ne provnum_ne VISIBLE NONE;gadm_level gadm_level VISIBLE NONE;check_me check_me VISIBLE NONE;scalerank scalerank VISIBLE NONE;datarank datarank VISIBLE NONE;abbrev abbrev VISIBLE NONE;postal postal VISIBLE NONE;area_sqkm area_sqkm VISIBLE NONE;sameascity sameascity VISIBLE NONE;labelrank labelrank VISIBLE NONE;featurecla featurecla VISIBLE NONE;admin admin VISIBLE NONE;name_len name_len VISIBLE NONE;mapcolor9 mapcolor9 VISIBLE NONE;mapcolor13 mapcolor13 VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE")

# Process: Feature Class To Shapefile (multiple) (2)...
gp.FeatureClassToShapefile_conversion("ne_10m_admin_1_states_provinces_lakes_shp", v10m_cultural__3_)

# Process: Make Feature Layer (2)...
gp.MakeFeatureLayer_management(ne_10m_admin_1_states_provinces_geodb_tmp__4_, ne_10m_admin_1_states_provinces_shp, "", "", "adm1_code adm1_code VISIBLE NONE;diss_me diss_me VISIBLE NONE;adm1_code adm1_code VISIBLE NONE;iso_3166_2 iso_3166_2 VISIBLE NONE;wikipedia wikipedia VISIBLE NONE;sr_sov_a3 sr_sov_a3 VISIBLE NONE;sr_adm0_a3 sr_adm0_a3 VISIBLE NONE;iso_a2 iso_a2 VISIBLE NONE;adm0_sr adm0_sr VISIBLE NONE;admin0_labelr admin0_labelr VISIBLE NONE;name name VISIBLE NONE;name_alt name_alt VISIBLE NONE;name_local name_local VISIBLE NONE;type type VISIBLE NONE;type_en type_en VISIBLE NONE;code_local code_local VISIBLE NONE;code_hasc code_hasc VISIBLE NONE;note note VISIBLE NONE;hasc_maybe hasc_maybe VISIBLE NONE;region region VISIBLE NONE;region_code region_code VISIBLE NONE;region_big region_big VISIBLE NONE;big_code big_code VISIBLE NONE;provnum_ne provnum_ne VISIBLE NONE;gadm_level gadm_level VISIBLE NONE;check_me check_me VISIBLE NONE;scalerank scalerank VISIBLE NONE;datarank datarank VISIBLE NONE;abbrev abbrev VISIBLE NONE;postal postal VISIBLE NONE;area_sqkm area_sqkm VISIBLE NONE;sameascity sameascity VISIBLE NONE;labelrank labelrank VISIBLE NONE;featurecla featurecla VISIBLE NONE;admin admin VISIBLE NONE;name_len name_len VISIBLE NONE;mapcolor9 mapcolor9 VISIBLE NONE;mapcolor13 mapcolor13 VISIBLE NONE")

# Process: Feature Class To Shapefile (multiple) (3)...
gp.FeatureClassToShapefile_conversion("ne_10m_admin_1_states_provinces_shp", v10m_cultural__6_)

